[versions]
plugin-android = "8.3.1"
plugin-kotlin = "1.9.23"
plugin-ksp = "1.9.23-1.0.19"

jecnaAPI = "5.0.0"

compose-compiler = "1.5.11"
compose-android-bom = "2024.03.00"

composeDestinations = "1.9.53"
composeStateEvents = "2.2.0"
composeHtml = "1.0.2"
composeCoil = "2.6.0"

activity = "1.8.2"

hilt-dagger = "2.51"
hilt-android = "1.2.0"
work = "2.9.0"
datastore = "1.0.0"
serialization = "1.6.3"

[libraries]
jecnaAPI = { module = "com.github.Tomasan7.JecnaAPI:jecnaapi", version.ref = "jecnaAPI" }

compose-android-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-android-bom" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
activity-compose = { module = "androidx.activity:activity-compose" }

composeDestinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "composeDestinations" }
composeDestinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestinations" }
composeStateEvents = { module = "com.github.leonard-palm:compose-state-events", version.ref = "composeStateEvents" }
composeHtml = { module = "com.github.ireward:compose-html", version.ref = "composeHtml" }
composeCoil = { module = "io.coil-kt:coil-compose", version.ref = "composeCoil" }

activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }

hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-android" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-dagger" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-dagger" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-android" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-android" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-android" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "plugin-kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "plugin-ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin-kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "plugin-kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-dagger" }
